
language: node_js

sudo: required

node_js: --lts

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - touch CNAME
    - echo "prelude.cc" > CNAME
    - git init
    - git config user.name "imyangmo" # 修改name
    - git config user.email "imyangmo@gmail.com" # 修改email
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${REPO_TOKEN}@github.com/imyangmo/imyangmo.github.io.git" master:master